steps:
# 1. Build nativo simples
- name: "gcr.io/cloud-builders/docker"
  args: ["build", "-t", "gcr.io/$PROJECT_ID/soraya-react:$COMMIT_SHA", "."]

# 2. Envia a imagem final pronta para o Container Registry do GCP
- name: "gcr.io/cloud-builders/docker"
  args: ["push", "gcr.io/$PROJECT_ID/soraya-react:$COMMIT_SHA"]

# 3. Faz o deploy automatizado dessa imagem na sua conta do Cloud Run
- name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
  entrypoint: gcloud
  args:
    - "run"
    - "deploy"
    - "soraya-react"
    - "--image"
    - "gcr.io/$PROJECT_ID/soraya-react:$COMMIT_SHA"
    - "--region"
    - "us-central1"
    - "--allow-unauthenticated"
    - "--port"
    - "8080"

images:
  - "gcr.io/$PROJECT_ID/soraya-react:$COMMIT_SHA"

