server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    # Importa os MIME types corretos
    include /etc/nginx/mime.types;

    # Cabeçalhos de Segurança
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-XSS-Protection "1; mode=block" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header Referrer-Policy "no-referrer-when-downgrade" always;
    # (Atenção: A política CSP foi omitida para não bloquear os websockets e iframes do Firebase, mas pode ser adicionada no futuro)

    # Configuração principal para o React Router (SPA)
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Configuração de cache para arquivos estáticos (melhora o desempenho)
    location ~* \.(?:ico|css|js|gif|jpe?g|png|woff2?|eot|ttf|svg)$ {
        expires 6M;
        access_log off;
        add_header Cache-Control "public, max-age=15552000, immutable";
    }
}